### ISSUE TITLE
Lots of issues getting table names

### ISSUE THREAD

**Issue by rcyost** [us-bea/beaapi#4]
Having lots of issues with getting the table names out of the API.

**Comment by bquistorff** [comment]
Thanks for your comment. This can be difficult. The information varies depending on the dataset queried, both due to the underlying API implementation and that in some areas the API data are not structured similar to the tables in iTables. A few options:
1. Sometimes the table name is returned as table metadata, typically in the "Notes" key: `tbl.attrs['detail']['Notes']`. See the `README.md` for an example.
2. Other information may be available. You can check first in the [API userguide](https://apps.bea.gov/api/_pdf/bea_web_service_api_user_guide.pdf). This packages documentation also lists [additional resources](https://us-bea.github.io/beaapi/iTables_to_api.html#Other-resources), such as the table registers.
